runtime: python312

instance_class: F2

# entrypoint: gunicorn -b :$PORT main:app

env_variables:
  JUPYTERHUB_API_URL:   "https:/galyleojupyter-beta.engagelively.com/hub/api"
  JUPYTER_HUB_API_TOKEN:   "bce4e024f2334725b8723db758aa5948"
  JUPYTERHUB_URL:   "https:/galyleojupyter-beta.engagelively.com"
  GALYLEO_SERVICE_API_TOKEN:   "djfkdsjjkdfk"
  GALYLEO_CLIENT_ID:   "service-galyleo"
  GALYLEO_ROOT_URL:   "https:/galyleojupyter-beta.engagelively.com/services/galyleo"
  GALYLEO_PERMISSIONS_DATABASE:   "galyleo-server"
  GALYLEO_PERMISSIONS_NAMESPACE:   "galyleo-server"
  GOOGLE_PROJECT:   "galyleo-server-2"
  BUCKET_NAME:   "galyleo-server-2-test-bucket"
  GALYLEO_SECRET_KEY:   "02486733472136175476809643230687"


handlers:
  - url: /.*
    redirect_http_response_code: 301
    script: auto